# Generated by Django 5.0.7 on 2025-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Адрес электронной почты')),
                ('service', models.CharField(blank=True, choices=[('deep_cleaning', 'Общий клининг'), ('general_cleaning', 'Генеральная уборка'), ('construction_cleaning', 'Послестроительная уборка'), ('carpet_cleaning', 'Химчистка ковров и мебели')], max_length=50, verbose_name='Вид услуги')),
                ('is_custom_service', models.BooleanField(default=False, verbose_name='Иная услуга')),
                ('custom_service', models.TextField(blank=True, null=True, verbose_name='Описание иной услуги')),
                ('date_and_time', models.DateTimeField(verbose_name='Дата и время')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=50, verbose_name='Тип оплаты')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('ip_progress', 'В работе'), ('done', 'Выполнено'), ('cancelled', 'Отменено')], default='new', max_length=50, verbose_name='Статус')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
